### ISSUE TITLE
Damage Tilt Bug

### ISSUE THREAD

**Issue by Trigam04** [MarshDeer/howlongmojang#13]
The damage tilt bug can finally be removed as it has been fixed in 23w03a
https://www.minecraft.net/en-us/article/minecraft-snapshot-23w03a
https://bugs.mojang.com/browse/MC-26678

**Comment by MarshDeer** [comment]
Hi! I'll fix this later today after I'm off work~
I was vaguely aware they had done something regarding this bug, but I couldn't get the energy to actually update the website as I'm not really interested in Minecraft atm ^^; but since all the info is here I might as well update it so at least it doesn't have factually inaccurate info. Thanks!

**Comment by MarshDeer** [comment]
Fixed by commit 9a00458
